### PR TITLE
Only load selected card data

### PR DESCRIPTION
**Pull request by MeidoDev**
When dragging a card into the game window, only those parts of the data will be loaded which are selected by the check boxes on the "Load card" window.

### CODE REVIEW

**Comment by im-mi** [comment]
I like this feature and there are some compelling usage cases for it. However, it seems a little counter-intuitive given that the regular character load menu is otherwise bypassed. I can imagine a user being confused as to why a character isn't being fully loaded since it isn't readily apparent why. That's why I think there needs to be an indication of how the two UIs are related.

The only way I've thought of to do that is to show a visible log message each time a character gets loaded detailing which parts were actually loaded. However, it would look a bit ugly and would cheapen said messages which are currently used only for warnings and errors. It could be minimized by using different text colors (red for error, yellow for warning, etc.), but it would still look pretty bad overall.

I'm still undecided on this one.

**Comment by MeidoDev** [comment]
I actually had considered this problem as well while implementing. On the other hand, the Chara Maker is initialized with all options checked, so unless the user explicitly turns them off the plugin will keep behaving as expected. Still, as you said, there will most likely be confused people due to this functionality.

One quick "solution" I can think of is making the feature opt-in via a config flag, using the Bepis `Config` helper.

**Comment by im-mi** [comment]
After thinking about it some more, I've decided that this feature is a little more complicated than I'm going for, even if locked behind a config setting. However, please feel free to keep your own fork up with more advanced features like this.

**Comment by MeidoDev** [comment]
Alright, thanks for your feedback!

**Comment by im-mi** [comment]
Welp, people just keep bugging me for this feature, so you win I guess. Added in https://github.com/im-mi/KoikatuDragAndDrop/pull/4 (based on _your_ code, no less!).

I still think it's a little counter-intuitive, but people really seem to want it. \*shrug\*

Anyway, thanks for the contribution.

**Pull request closed without merging**
